name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Build Chrome Extension
        run: npm run build
      - name: List chrome-mv3 output directory
        run: |
          if [ -d .output/chrome-mv3 ]; then
            echo ".output/chrome-mv3 exists!"
            ls -l .output/chrome-mv3
          else
            echo ".output/chrome-mv3 does not exist!"
          fi
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - name: Upload chrome-mv3 directory
        uses: actions/upload-artifact@v4
        with:
          name: chrome-mv3
          path: .output/chrome-mv3
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
